apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: diffusers-runtime
spec:
  predictor:
    containers:
      - name: kserve-container
        image: quay.io/cfchase/diffusers-runtime:latest
